//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjHosNav
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbHospitalEntities1 : DbContext
    {
        public dbHospitalEntities1()
            : base("name=dbHospitalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tExamination> tExamination { get; set; }
        public virtual DbSet<tMedicine> tMedicine { get; set; }
        public virtual DbSet<tMember> tMember { get; set; }
        public virtual DbSet<tMyMedicineBox> tMyMedicineBox { get; set; }
        public virtual DbSet<tOutpatient> tOutpatient { get; set; }
        public virtual DbSet<tReturn> tReturn { get; set; }
        public virtual DbSet<tSearch> tSearch { get; set; }
    }
}
