//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjHosNav
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMember()
        {
            this.tMyMedicineBox = new HashSet<tMyMedicineBox>();
        }
    
        public int MId { get; set; }
        public string MName { get; set; }
        public string MEmail { get; set; }
        public string MPassword { get; set; }
        public string MPhone { get; set; }
        public string MGender { get; set; }
        public string MAddress { get; set; }
        public string MAuthority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMyMedicineBox> tMyMedicineBox { get; set; }
    }
}
