//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjHosNav
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMyMedicineBox
    {
        public int fId { get; set; }
        public string fChName { get; set; }
        public string fImagePath { get; set; }
        public string fDayOfUse { get; set; }
        public string fQuantityUse { get; set; }
        public Nullable<int> MId { get; set; }
    
        public virtual tMember tMember { get; set; }
    }
}
